version: "3.1"

volumes:
  postgresql_data:
  ldap_data:
  ldap_config:
  geoserver_geodata:
  geoserver_datadir:
  geoserver_tiles:
  geoserver_native_libs:
  mapfishapp_uploads:
  extractorapp_extracts:
  geonetwork_datadir:
  datafeeder_uploads:

secrets:
  slapd_password:
    file: ./secrets/slapd_password.txt
  geoserver_privileged_user_passwd:
    file: ./secrets/geoserver_privileged_user_passwd.txt

services:
  database:
    image: georchestra/database:latest
    environment:
      - POSTGRES_USER=georchestra
      - POSTGRES_PASSWORD=georchestra
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: unless-stopped

  ldap:
    image: georchestra/ldap:latest
    secrets:
      - slapd_password
      - geoserver_privileged_user_passwd
    environment:
        - SLAPD_ORGANISATION=georchestra
        - SLAPD_DOMAIN=georchestra.org
        - SLAPD_PASSWORD_FILE=/run/secrets/slapd_password
        - SLAPD_PASSWORD=
        - GEOSERVER_PRIVILEGED_USER_PASSWORD_FILE=/run/secrets/geoserver_privileged_user_passwd
        - SLAPD_LOG_LEVEL=32768 # See https://www.openldap.org/doc/admin24/slapdconfig.html#loglevel%20%3Clevel%3E
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap
    restart: unless-stopped

  proxy:
    image: georchestra/security-proxy:latest
    depends_on:
      - ldap
      - database
    volumes:
      - ./config:/etc/georchestra
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - XMS=256M
      - XMX=1G
    restart: unless-stopped

  cas:
    image: georchestra/cas:latest
    depends_on:
      - ldap
    volumes:
      - ./config:/etc/georchestra
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - XMS=256M
      - XMX=1G
    restart: unless-stopped

  header:
    image: georchestra/header:latest
    volumes:
      - ./config:/etc/georchestra
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - XMS=256M
      - XMX=512M
    restart: unless-stopped

  #~ mapfishapp:
    #~ image: georchestra/mapfishapp:latest
    #~ depends_on:
      #~ - database
    #~ volumes:
      #~ - ./config:/etc/georchestra
      #~ - mapfishapp_uploads:/mnt/mapfishapp_uploads
    #~ environment:
      #~ - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      #~ - XMS=256M
      #~ - XMX=2G
    #~ restart: unless-stopped

  #~ extractorapp:
    #~ image: georchestra/extractorapp:latest
    #~ depends_on:
      #~ - database
    #~ volumes:
      #~ - ./config:/etc/georchestra
      #~ - extractorapp_extracts:/mnt/extractorapp_extracts
    #~ environment:
      #~ - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      #~ - XMS=256M
      #~ - XMX=2G
    #~ restart: unless-stopped

  #~ geoserver:
    #~ image: georchestra/geoserver:latest
    #~ depends_on:
      #~ - ldap
    #~ volumes:
      #~ - ./config:/etc/georchestra
      #~ - geoserver_datadir:/mnt/geoserver_datadir
      #~ - geoserver_geodata:/mnt/geoserver_geodata
      #~ - geoserver_tiles:/mnt/geoserver_tiles
      #~ - geoserver_native_libs:/mnt/geoserver_native_libs
    #~ environment:
      #~ - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      #~ - XMS=256M
      #~ - XMX=2G
    #~ restart: unless-stopped

  #~ console:
    #~ image: georchestra/console:latest
    #~ depends_on:
      #~ - ldap
      #~ - database
    #~ volumes:
      #~ - ./config:/etc/georchestra
    #~ environment:
      #~ - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      #~ - XMS=256M
      #~ - XMX=1G
    #~ restart: unless-stopped

  #~ geonetwork:
    #~ image: georchestra/geonetwork:latest
    #~ depends_on:
      #~ - ldap
      #~ - database
    #~ volumes:
      #~ - ./config:/etc/georchestra
      #~ - geonetwork_datadir:/mnt/geonetwork_datadir
    #~ environment:
      #~ - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      #~ - XMS=256M
      #~ - XMX=3G
    #~ restart: unless-stopped

  #~ analytics:
    #~ image: georchestra/analytics:latest
    #~ depends_on:
      #~ - database
    #~ volumes:
      #~ - ./config:/etc/georchestra
    #~ environment:
      #~ - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      #~ - XMS=256M
      #~ - XMX=1G
    #~ restart: unless-stopped

  #~ mapstore:
    #~ image: georchestra/mapstore:latest
    #~ depends_on:
      #~ - database
    #~ volumes:
      #~ - ./config:/etc/georchestra
    #~ environment:
      #~ - JAVA_OPTS=-Xms512m -Xmx512m -XX:MaxPermSize=128m -Dgeorchestra.datadir=/etc/georchestra -DPRINT_BASE_URL=pdf
    #~ restart: unless-stopped

  #~ datafeeder:
    #~ image: georchestra/datafeeder:latest
    #~ volumes:
      #~ - ./config:/etc/georchestra
      #~ - datafeeder_uploads:/tmp/datafeeder
    #~ environment:
      #~ - JAVA_OPTS=-Xms512m -Xmx512m -XX:MaxPermSize=128m
    #~ restart: unless-stopped

  #~ import:
    #~ image: georchestra/datafeeder-frontend:21.0-SNAPSHOT
    #~ volumes:
      #~ - ./config:/etc/georchestra
    #~ restart: unless-stopped
