version: "3"

volumes:
  geowebcache_tiles:
  geowebcache_datadir:

services:

  # standalone geowebcache:
  geowebcache:
    image: georchestra/geowebcache:20.0.x
    volumes:
      - geowebcache_datadir:/mnt/geowebcache_datadir
      - geowebcache_tiles:/mnt/geowebcache_tiles
      - ./config:/etc/georchestra
    environment:
      - XMS=1G
      - XMX=2G
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
#    ports:
#      - 8080:8080
