version: "3.1"

# Complementary services, not part of geOrchestra core.
# They are made to ease your life as a developer.
# **NOT** production ready !

volumes:
  smtp_maildir:

services:
  traefik-me-certificate-downloader:
    image: alpine
    command: sh -c "cd /etc/ssl/traefik
      && wget traefik.me/fullchain.pem -O traefik.me.crt
      && wget traefik.me/privkey.pem -O traefik.me-key.pem"
    volumes:
      - ./resources/ssl:/etc/ssl/traefik

  georchestra-127-0-1-1.traefik.me:
    image: traefik:2.4
    depends_on:
      - traefik-me-certificate-downloader
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./resources/ssl:/etc/certs:ro
      - ./resources/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./resources/traefik-config.yml:/etc/traefik/config.yml:ro
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.rule=Host(`georchestra-127-0-1-1.traefik.me`) && (PathPrefix(`/traefik`) || PathPrefix(`/api`))"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=traefik-strip"
      - "traefik.http.middlewares.traefik-strip.stripprefix.prefixes=/traefik"

  proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.tls=true"
      - "traefik.http.routers.proxy.rule=Host(`georchestra-127-0-1-1.traefik.me`)"
      # CORS related. Open everything to the world.
      - "traefik.http.middlewares.corsheader.headers.accesscontrolallowmethods=GET, HEAD, POST, PUT, DELETE, OPTIONS, PATCH"
      - "traefik.http.middlewares.corsheader.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.corsheader.headers.accesscontrolmaxage=1800"
      - "traefik.http.middlewares.corsheader.headers.addvaryheader=true"
      - "traefik.http.middlewares.corsheader.headers.accesscontrolallowcredentials=true"
      - "traefik.http.routers.proxy.middlewares=corsheader@docker"

  cas:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cas.tls=true"
      - "traefik.http.routers.cas.rule=Host(`georchestra-127-0-1-1.traefik.me`) && PathPrefix(`/cas`)"

  smtp:
    image: camptocamp/smtp-sink:latest
    volumes:
      - smtp_maildir:/home/smtp/Maildir/
    restart: always

  courier-imap:
    image: camptocamp/courier-imap:latest
    volumes:
      - smtp_maildir:/home/smtp/Maildir/
    restart: always

  webmail:
    image: camptocamp/sqwebmail:latest
    environment:
      - IMAP_HOSTNAME=courier-imap
      - SMTP_HOSTNAME=smtp-sink
    volumes:
      - smtp_maildir:/home/smtp/Maildir/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webmail.tls=true"
      - "traefik.http.routers.webmail.rule=Host(`georchestra-127-0-1-1.traefik.me`) && PathPrefix(`/webmail`)"
    restart: always
