# Maps all backend services to predefined host ports
version: "3.1"

volumes:
  ldap2_data:
  ldap2_config:

services:
  gateway:
    environment:
      - JAVA_TOOL_OPTIONS=-Dgeorchestra.datadir=/etc/georchestra -Dspring.profiles.active=docker -Xmx512M -Dgeorchestra.gateway.security.ldap.ldap2.enabled=true -Dgeorchestra.gateway.security.ldap.ldap2.url=ldap://ldap2:389

  database:
    ports:
      - 54321:5432
  ldap:
    ports:
      - 3891:389

  ldap2:
    image: georchestra/ldap:latest
    secrets:
      - slapd_password
      - geoserver_privileged_user_passwd
    environment:
        - SLAPD_ORGANISATION=georchestra
        - SLAPD_DOMAIN=georchestra.org
        - SLAPD_PASSWORD_FILE=/run/secrets/slapd_password
        - SLAPD_PASSWORD=
        - GEOSERVER_PRIVILEGED_USER_PASSWORD_FILE=/run/secrets/geoserver_privileged_user_passwd
        - SLAPD_LOG_LEVEL=32768 # See https://www.openldap.org/doc/admin24/slapdconfig.html#loglevel%20%3Clevel%3E
    volumes:
      - ldap2_data:/var/lib/ldap
      - ldap2_config:/etc/ldap
    restart: always
    ports:
      - 3899:389
        
  proxy:
    ports:
      - 10000:8080
  cas:
    ports:
      - 10002:8080
  header:
    ports:
      - 10003:8080
  mapfishapp:
    ports:
      - 10004:8080
  extractorapp:
    ports:
      - 10005:8080
  geoserver:
    ports:
      - 10006:8080
  console:
    ports:
      - 10007:8080
  geonetwork:
    ports:
      - 5005:5005
      - 10008:8080
  analytics:
    ports:
      - 10009:8080
  mapstore:
    ports:
      - 10010:8080
  postgis:
    ports:
      - 54322:5432
  datafeeder:
    ports:
      - 10011:8080
  import:
    ports:
      - 10012:80
